baseURL = 'https://2060490154-github-io.pages.dev/'
languageCode = 'en-us'
title = 'My New Hugo Site'



	
themesDir = "themes"
theme = "hugo-theme-stack"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true

